import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.scss";
import Header from "@/components/global-header";
import Nav from "@/components/global-nav";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SPACEviewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Nav/>
        <main className="viewer">
          {children}
        </main>
      </body>
    </html>
  );
}
